# Generated by Django 3.0.8 on 2020-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeforcomment',
            name='liked',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='likeforpost',
            name='liked',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
