# Generated by Django 3.0.8 on 2020-08-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200815_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeforcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comment'),
        ),
        migrations.AlterField(
            model_name='likeforpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
    ]
